name: firebase_auth_youtube
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.10.0
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.6
  email_validator: ^2.0.1
  
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  firebase_core: ^2.24.2
  flutter_screenutil:
  equatable: ^2.0.5
  dots_indicator:
  user_repository:
    path: packages/user_repository
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.6
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/images/teams/

